/** localstorage key 存储我的文件树展开状态 */
export const MYBRICKS_WORKSPACE_DEFAULT_MY_FILETREE = "MYBRICKS_WORKSPACE_DEFAULT_MY_FILETREE";
/** localstorage key 存储协作组文件树展开状态 */
export const MYBRICKS_WORKSPACE_DEFAULT_GROUP_FILETREE = "MYBRICKS_WORKSPACE_DEFAULT_GROUP_FILETREE";
